---
- name: Create Consul service definition
  include_role: name=infra-role-consul-service
  vars:
    consul_config_name: '{{ octobox_service_name }}'
    consul_services:
      - name: '{{ octobox_service_name }}'
        tags: ['github', 'misc']
        # we advertise the port with basic auth
        port: '{{ octobox_app_cont_port }}'
        checks:
          - id: '{{ octobox_service_name }}-status'
            name: Octobox Healthcheck
            type: http
            http: 'http://localhost:{{ octobox_app_cont_port }}/'
